function Heur_trans_AeroFvsx(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  X2:  vector of plot x data
%  YMATRIX2:  matrix of plot y data

%  Auto-generated by MATLAB on 11-Jan-2025 09:43:13

% Set ratios and figure properties
% Create figure
hFIG = figure;
fname = "Heur_trans_AeroFvsx";

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1.5);
set(plot1(1),'DisplayName','Lift distribution over distance');
set(plot1(2),'DisplayName','Drag distribution over distance',...
    'LineStyle','--');

% Create multiple line objects using matrix input to plot
plot2 = plot(X2,YMatrix2,'LineWidth',1.5,'LineStyle','none');
set(plot2(1),'DisplayName','Break point for Lift','Marker','o',...
    'Color',[1 0 0]);
set(plot2(2),'DisplayName','Break point for Drag','Marker','^',...
    'Color',[1 0 1]);

% Create ylabel
ylabel('Aerodynamic forces [N]');

% Create xlabel
xlabel('x [m]');

% Create title
title('Horizontal distance [m] vs Aerodynamic Forces [N].');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','east');

picturewidth = 20;
hw_ratio = 0.65;
set(findall(hFIG,'-property','FontSize'),'FontSize',16)
set(findall(hFIG,'-property','Box'),'Box','off') % optional
set(findall(hFIG,'-property','Interpreter'),'Interpreter','latex') 
set(findall(hFIG,'-property','TickLabelInterpreter'),'TickLabelInterpreter','latex')
set(hFIG,'Units','centimeters','Position',[3 3 picturewidth hw_ratio*picturewidth])
pos = get(hFIG,'Position');
set(hFIG,'PaperPositionMode','Auto','PaperUnits','centimeters','PaperSize',[pos(3), pos(4)])
print(hFIG,fname,'-dpdf','-vector','-fillpage')