function RevHeur_RPSvsx(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  X2:  vector of plot x data
%  Y2:  vector of plot y data

%  Auto-generated by MATLAB on 11-Jan-2025 11:18:12

% Set ratios and figure properties
% Create figure
hFIG = figure;
fname = "RevHeur_RPSvsx";

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Engine revolutions distribution','LineWidth',1.5);

% Create plot
plot(X2,Y2,'DisplayName','Engine Tilt breakpoint','Marker','o',...
    'LineWidth',1.5,...
    'LineStyle','none',...
    'Color',[1 0 0]);

% Create yline
yline(78.125,'LineStyle','--','Color',[0 0 0],'LineWidth',1.5,'DisplayName','Max Engine speed');

% Create ylabel
ylabel('n [rps]');

% Create xlabel
xlabel('t [s]');

% Create title
title('Time [s] vs Eng. revolutions [rps].');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.482592075892857 0.750476189567929 0.361244419642857 0.0869047637212845]);


picturewidth = 20;
hw_ratio = 0.65;
set(findall(hFIG,'-property','FontSize'),'FontSize',16)
set(findall(hFIG,'-property','Box'),'Box','off') % optional
set(findall(hFIG,'-property','Interpreter'),'Interpreter','latex') 
set(findall(hFIG,'-property','TickLabelInterpreter'),'TickLabelInterpreter','latex')
set(hFIG,'Units','centimeters','Position',[3 3 picturewidth hw_ratio*picturewidth])
pos = get(hFIG,'Position');
set(hFIG,'PaperPositionMode','Auto','PaperUnits','centimeters','PaperSize',[pos(3), pos(4)])
print(hFIG,fname,'-dpdf','-vector','-fillpage')