function aero_models(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2, Y3, Y4)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  Y2:  vector of plot y data


%  Auto-generated by MATLAB on 06-Jan-2025 11:32:12

% Set ratios and figure properties
% Create figure
hFIG = figure;
fname = "aero_models";



% Create subplot
subplot1 = subplot(1,3,1);
hold(subplot1,'on');

% Create plot
plot(X1,Y2,"LineWidth",1.2);

% Create ylabel
ylabel('$C_L$ [-]');

% Create xlabel
xlabel('Angle of attack ($\alpha$)');



box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'off');
% Create subplot
subplot2 = subplot(1,3,2);
hold(subplot2,'on');

% Create plot
plot(X1,Y1,"LineWidth",1.2);

% Create ylabel
ylabel('$C_D$ [-]');

% Create xlabel
xlabel('Angle of attack ($\alpha$)');


box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'off');


% Create subplot
subplot3 = subplot(1,3,3);
hold(subplot3,'on');

% Create plot
plot(X1,Y2./Y1,"LineWidth",1.2);

% Create ylabel
ylabel('Aerodynamic Efficiency $C_L/C_D$ [-]');

% Create xlabel
xlabel('Angle of attack ($\alpha$)');


box(subplot3,'on');
grid(subplot3,'on');
hold(subplot3,'off');


% Create title
sgtitle("Aircraft Aerodynamic Coefficients Models vs Angle of Attack");
picturewidth = 20;
hw_ratio = 0.65;
set(findall(hFIG,'-property','FontSize'),'FontSize',16)
set(findall(hFIG,'-property','Box'),'Box','off') % optional
set(findall(hFIG,'-property','Interpreter'),'Interpreter','latex') 
set(findall(hFIG,'-property','TickLabelInterpreter'),'TickLabelInterpreter','latex')
set(hFIG,'Units','centimeters','Position',[3 3 picturewidth hw_ratio*picturewidth])
pos = get(hFIG,'Position');
set(hFIG,'PaperPositionMode','Auto','PaperUnits','centimeters','PaperSize',[pos(3), pos(4)])
print(hFIG,fname,'-dpdf','-vector','-fillpage')
%print(hFIG,fname,'-dpng','-vector')
