function Heur_trans_Tvsx(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  X2:  vector of plot x data
%  Y2:  vector of plot y data

%  Auto-generated by MATLAB on 11-Jan-2025 09:39:45

% Set ratios and figure properties
% Create figure
hFIG = figure;
fname = "Heur_trans_Tvsx";

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Thrust distribution over distance',...
    'LineWidth',1.5);

% Create plot
plot(X2,Y2,'DisplayName','Break point','Marker','o','LineWidth',1.5,...
    'LineStyle','none',...
    'Color',[1 0 0]);

% Create yline
yline(476.766,'DisplayName','Max Thrust','LineStyle','--','Color',[0 0 0],...
    'LineWidth',1.5);

% Create ylabel
ylabel('T [N]');

% Create xlabel
xlabel('x [m]');

% Create title
title('Horizontal distance [m] vs Thrust [N]. Phase break at 443.1561 N.');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.621168172357626 0.719521298359356 0.131116043491865 0.0639732735723771]);

picturewidth = 20;
hw_ratio = 0.65;
set(findall(hFIG,'-property','FontSize'),'FontSize',16)
set(findall(hFIG,'-property','Box'),'Box','off') % optional
set(findall(hFIG,'-property','Interpreter'),'Interpreter','latex') 
set(findall(hFIG,'-property','TickLabelInterpreter'),'TickLabelInterpreter','latex')
set(hFIG,'Units','centimeters','Position',[3 3 picturewidth hw_ratio*picturewidth])
pos = get(hFIG,'Position');
set(hFIG,'PaperPositionMode','Auto','PaperUnits','centimeters','PaperSize',[pos(3), pos(4)])
print(hFIG,fname,'-dpdf','-vector','-fillpage')