function HvstOC50_fig(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 06-Jan-2025 12:53:34

% Set ratios and figure properties
% Create figure
hFIG = figure;
fname = "HvstOC50";

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',1.5,'Color',[0 0.447058823529412 0.741176470588235]);

% Create ylabel
ylabel('h [m]');

% Create xlabel
xlabel('t [s]');

% Create title
title('VTOL Take off Trajectory');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');

picturewidth = 20;
hw_ratio = 0.65;
set(findall(hFIG,'-property','FontSize'),'FontSize',16)
set(findall(hFIG,'-property','Box'),'Box','off') % optional
set(findall(hFIG,'-property','Interpreter'),'Interpreter','latex') 
set(findall(hFIG,'-property','TickLabelInterpreter'),'TickLabelInterpreter','latex')
set(hFIG,'Units','centimeters','Position',[3 3 picturewidth hw_ratio*picturewidth])
pos = get(hFIG,'Position');
set(hFIG,'PaperPositionMode','Auto','PaperUnits','centimeters','PaperSize',[pos(3), pos(4)])
print(hFIG,fname,'-dpdf','-vector','-fillpage')
