function VTOL_1(X1, Y1, Y2, Y3, Y4)
%CREATEFIGURE(X1, Y1, Y2, Y3, Y4)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  Y2:  vector of plot y data
%  Y3:  vector of plot y data
%  Y4:  vector of plot y data

%  Auto-generated by MATLAB on 06-Jan-2025 11:32:12


% Create subplot
subplot1 = subplot(2,2,1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,"LineWidth",1.2);

% Create ylabel
ylabel('height [m]');

% Create xlabel
xlabel('time (s)');

% Create title
title('VTOL Take off Trajectory');

box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'off');
% Create subplot
subplot2 = subplot(2,2,2);
hold(subplot2,'on');

% Create plot
plot(X1,Y2,"LineWidth",1.2);

% Create ylabel
ylabel('Energy [J]');

% Create xlabel
xlabel('time (s)');

% Create title
title('VTOL Energy discharge');

box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'off');
% Create subplot
subplot3 = subplot(2,2,3);
hold(subplot3,'on');

% Create plot
plot(X1,Y3,"LineWidth",1.2);

% Create ylabel
ylabel('velocity [m/s]');

% Create xlabel
xlabel('time (s)');

% Create title
title('Aircraft velocity distribution');

box(subplot3,'on');
grid(subplot3,'on');
hold(subplot3,'off');
% Create subplot
subplot4 = subplot(2,2,4);
hold(subplot4,'on');

% Create plot
plot(X1,Y4,"LineWidth",1.2);

% Create ylabel
ylabel('Engine revolutions [rps]');

% Create xlabel
xlabel('time (s)');

% Create title
title('Engine control');

box(subplot4,'on');
grid(subplot4,'on');
hold(subplot4,'off');


% Set ratios and figure properties
% Create figure
hFIG = figure;
fname = "VTOL_OptControl_100";

picturewidth = 20;
hw_ratio = 0.65;
set(findall(hFIG,'-property','FontSize'),'FontSize',10)
set(findall(hFIG,'-property','Box'),'Box','off') % optional
set(findall(hFIG,'-property','Interpreter'),'Interpreter','latex') 
set(findall(hFIG,'-property','TickLabelInterpreter'),'TickLabelInterpreter','latex')
set(hFIG,'Units','centimeters','Position',[3 3 picturewidth hw_ratio*picturewidth])
pos = get(hFIG,'Position');
set(hFIG,'PaperPositionMode','Auto','PaperUnits','centimeters','PaperSize',[pos(3), pos(4)])
print(hFIG,fname,'-dpdf','-vector','-fillpage')
%print(hFIG,fname,'-dpng','-vector')
