function RevHeur_angletime(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  X2:  vector of plot x data
%  YMATRIX2:  matrix of plot y data

%  Auto-generated by MATLAB on 11-Jan-2025 01:46:52


% Set ratios and figure properties
% Create figure
hFIG = figure;
fname = "RevHeur_angletime";

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1.5);
set(plot1(1),'DisplayName','Engine inclination w.r.t. airflow');
set(plot1(2),'DisplayName', 'Engine tilt angle');
set(plot1(3),'DisplayName','Angle of attack');

% Create multiple line objects using matrix input to plot
plot2 = plot(X2(1),YMatrix2(1),'LineWidth',1.5,'LineStyle','none','Color',[1 0 0]);
set(plot2(1),'DisplayName','Engine Tilt breakpoint for $\phi$','Marker','o');

% Create multiple line objects using matrix input to plot
plot3 = plot(X2(2),YMatrix2(2),'LineWidth',1.5,'LineStyle','none','Color',[1 0 0]);
set(plot3(1),'DisplayName','Engine Tilt breakpoint for $\epsilon$','Marker','^');

% Create multiple line objects using matrix input to plot
plot4 = plot(X2(3),YMatrix2(3),'LineWidth',1.5,'LineStyle','none','Color',[1 0 0]);
set(plot4(1),'DisplayName','Engine Tilt breakpoint for $\alpha$' ,...
    'Marker','*');

% Create ylabel
ylabel('Relevant performance angles [deg]');

% Create xlabel
xlabel('t [s]');

% Create title
title('Time [s] vs Engine tilt angle [deg].');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.637306551059087 0.495067537312064 0.143125 0.116928411989796]);

picturewidth = 20;
hw_ratio = 0.65;
set(findall(hFIG,'-property','FontSize'),'FontSize',16)
set(findall(hFIG,'-property','Box'),'Box','off') % optional
set(findall(hFIG,'-property','Interpreter'),'Interpreter','latex') 
set(findall(hFIG,'-property','TickLabelInterpreter'),'TickLabelInterpreter','latex')
set(hFIG,'Units','centimeters','Position',[3 3 picturewidth hw_ratio*picturewidth])
pos = get(hFIG,'Position');
set(hFIG,'PaperPositionMode','Auto','PaperUnits','centimeters','PaperSize',[pos(3), pos(4)])
print(hFIG,fname,'-dpdf','-vector','-fillpage')